### ISSUE TITLE
ctrl|cmd+shift+enter behaves differently than IntelliJ.

### ISSUE THREAD

**Issue by weakish** [k--kato/vscode-intellij-idea-keybindings#13]
vscode actually just open up a new line and move to it.

Probably a good idea to add a note to the comparison list.

**Comment by k--kato** [comment]
## Environment

Editor | Version | OS | Command | Action
-------|----------|-----|------------|---------
IntelliJ IDEA | 2016.2.4 | Windows 10 | Ctrl+Shift+Enter | Choose Lookup Item and Invoke Complete Statement
VS Code | 1.5.2 (IntelliJ IDEA Keybindings Ver.0.1.5) | Windows 10 | Ctrl+Shift+Enter | editor.action.insertLineAfter


## OK 
![intellij_2016 2 4](https://cloud.githubusercontent.com/assets/10364603/18577193/abd75fbe-7c22-11e6-9393-3ffd32e0e4d4.gif)

![vscode_intellij_0 1 5](https://cloud.githubusercontent.com/assets/10364603/18577207/dd3539aa-7c22-11e6-9b48-330b3ddecb23.gif)


## NG ?

![intellij_2016 2 4_suggest](https://cloud.githubusercontent.com/assets/10364603/18577432/a359bc86-7c24-11e6-9221-5eb3bc318ab5.gif)

![vscode_intellij_0 1 5_suggest](https://cloud.githubusercontent.com/assets/10364603/18577436/a782640c-7c24-11e6-951b-144c354ba78f.gif)
