### ISSUE TITLE
Column (box) text selection not implemented

### ISSUE THREAD

**Issue by skysteve** [k--kato/vscode-intellij-idea-keybindings#15]
The shortcut in VSC for this is shit+alt+(mouse click)

https://code.visualstudio.com/docs/editor/editingevolved#_column-box-text-selection

In IDEA it's just alt+(mouse click)

https://www.jetbrains.com/help/webstorm/2016.2/selecting-text-in-the-editor.html

**Comment by k--kato** [comment]
@skysteve 
There is two issues.

1. VS Code can't bind keys to `mouse click`: https://code.visualstudio.com/docs/customization/keybindings#_accepted-keys
1. The command id `column box text selection` is not available: https://code.visualstudio.com/docs/customization/keybindings#_basic-editing

**Comment by skysteve** [comment]
Fair enough

**Comment by k--kato** [comment]
😥
