### ISSUE TITLE
Issue with Updating Extension and Versions

### ISSUE THREAD

**Issue by jpshelley** [k--kato/vscode-intellij-idea-keybindings#27]
I just installed VSCode today and setting up my extensions. This extensions shows its on version `0.1.1` in the extension panel. This is not allowing me to get the bug fixes coming through such as the formatting and close active editor mentioned in previous comments.
Is there another way to install or does an update need to go out for the extension to recognize it?

![screen shot 2016-11-16 at 3 51 56 pm](https://cloud.githubusercontent.com/assets/2798846/20367382/d6cd4a54-ac14-11e6-80d0-bfcc767b60cc.png)

**Comment by k--kato** [comment]
@jpshelley Thanks! `Format Document` / `Format Selection` command compatibility with a minimum VS Code version of 1.7.x. I fixed the package.json `engines`.

[October 2016 (version 1.7), Format Document / Format Selection](https://code.visualstudio.com/updates/v1_7#_format-document-format-selection)
