### ISSUE TITLE
alt+1 should toggle close corresponding tool window instead of just opening

### ISSUE THREAD

**Issue by thekalinga** [k--kato/vscode-intellij-idea-keybindings#36]
`alt+1` in windows/linux
`cmd+1` in max

should toggle corresponding tool window status, instead of just opening.

**Comment by thekalinga** [comment]
Thanks for the fix

**Comment by k--kato** [comment]
@thekalinga Many thanks!

**Comment by thekalinga** [comment]
Currently, `alt+1` is properly behaving only if either

1. left explorer panel is not opened
2. left panel is opened & is in either explorer/extension/git tab

It is however is not working if you go to `debug` tab on left panel/`find in all files` & press `alt+1`

`alt+1` should always toggle the left panel to either show/hide left explorer pane
