### ISSUE TITLE
shift+esc can be mapped to ctrl+j

### ISSUE THREAD

**Issue by thekalinga** [k--kato/vscode-intellij-idea-keybindings#40]
`shift+esc` to hide panel can be mapped to `ctrl+j` which maps to `hide panel` action in vscode

**Comment by thekalinga** [comment]
The fix you gave is not hiding the panel instead hiding last opened editor.

To test why it is not working, open an embedded terminal & press `shift+esc`. You will notice that it is not hiding.

`shift+esc` should hide the panel, not `active or last active window`

**Comment by k--kato** [comment]
* `shift+esc`
  * ✅ side panel (Explorer, Find, Git, Debug, Extension) 
  * ✅ terminal
  * N/A output, cause [No workbench action to hide panel #14779](https://github.com/Microsoft/vscode/issues/14779)

**Comment by thekalinga** [comment]
I just verified for terminal, `shift+esc` is not working for terminal.

Version info
--

Version 1.8.0-insider
Commit be33bcdb2beb2d01c76ec8f830a70feaaa6721f5
Date 2016-12-01T09:40:51.017Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
IDEA Plugin version: 0.2.5

**Comment by thekalinga** [comment]
> N/A output, cause No workbench action to hide panel #14779

This is not valid anymore as you have `close panel` action in vscode.

**Comment by thekalinga** [comment]
shift+esc is not working for problems/errors view aswell
