### ISSUE TITLE
Ctrl+f4 is not working the latest version of close VsCode Insider builds

### ISSUE THREAD

**Issue by thekalinga** [k--kato/vscode-intellij-idea-keybindings#44]
When I try to close the active editor using `ctrl+f4` I get the following error.

Command `workbench.files.action.closeFile` has been removed. You can use `workbench.action.closeActiveEditor` instead

**Comment by k--kato** [comment]
@thekalinga 
duplicated #8
fixed #9

**Comment by k--kato** [comment]
@thekalinga 
When I download IntelliJ extension  using Insider builds 1.8.0, the extension version is v0.1.1 instead of v0.2.4. This is really weird thing...

<img width="512" alt="image" src="https://cloud.githubusercontent.com/assets/10364603/20798804/83ada74a-b823-11e6-9b9a-1a7c621e303b.png">

**Comment by k--kato** [comment]
@thekalinga 
Please try manual install VSIX (`Extensions: Install from VSIX`), temporary.
[intellij-idea-keybindings-0.2.5.vsix](https://github.com/k--kato/vscode-intellij-idea-keybindings/releases/download/v0.2.5/intellij-idea-keybindings-0.2.5.vsix)

**Comment by thekalinga** [comment]
I have installed 0.2.4, `alt+1` does not work along with various other shortcuts.

Auto update of extension for IntelliJ extension did not work. I had to uninstall & re-install the app.

**Comment by thekalinga** [comment]
Sorry.. `alt+1` is working, but not correctly. It is currently toggling left sidebar.

i.e if you have extensions sidebar open, and if you press `alt+1`, we should see explorer & if we press `alt+1` again, the panel should be hidden.

Pressing `alt+1` should toggle hiding and showing explorer.

`shift+esc` should hide all panels (terminal, output) & sidebar panel.

Please try this Intellij before giving the fix. Thanks.

**Comment by thekalinga** [comment]
Please note that `shift+esc` focus dependent, meaning, if you press `shift+esc` when you are in editor, it should not do anything. `shift+esc` should hide only the panel/sidebar that is currently having the focus.

**Comment by thekalinga** [comment]
Don't mean to push you.. Just checking to see if I can help..

Is there any blocker in fixing this?

Thanks
