### ISSUE TITLE
Line comment not working with numpad

### ISSUE THREAD

**Issue by mathiasfrohlich** [k--kato/vscode-intellij-idea-keybindings#5]
This is not a Issue, more a notification.
Commenting and uncommenting in Intellij works with numpad and in the best way on Nordic Keyboards.

This might be added with the following code to accommodate for this.
 
```
{
	"key": "ctrl+numpad_divide",
	"mac": "cmd+numpad_divide",
	"command": "editor.action.commentLine",
	"when": "editorTextFocus"
	"intellij": "Comment/uncomment with line comment using Numpad"

}
```

**Comment by k--kato** [comment]
@mathiasfrohlich 
Thanks! Fixed with v0.1.2
