### ISSUE TITLE
ctrl+s bug

### ISSUE THREAD

**Issue by gaoyuanfell** [k--kato/vscode-intellij-idea-keybindings#52]
Modify the HTML file to modify the JS file, save the contents of the HTML file will be pasted into the JS file inside

**Comment by ixoster** [comment]
I stoped using this extension after found this bug! need fix

**Comment by k--kato** [comment]
@gaoyuanfell Can you explain with gif animation?

**Comment by k--kato** [comment]
@gaoyuanfell @ixoster I just fixed and released v0.2.11. Please check it out 🎹

**Comment by jibbers42** [comment]
I'm not sure I understand what the reported bug is - can you explain it?

I found this bug because ctrl+s stopped saving all files, even though they hotkey is still described as "Save all". <https://github.com/k--kato/vscode-intellij-idea-keybindings/commit/351d3a5ca4a1fc34b2c958ad2189e6d2f436b419>
```
             {
                 "key": "ctrl+s",
                 "mac": "cmd+s",
-                "command": "workbench.action.files.saveAll",
+                "command": "workbench.action.files.save",
                 "intellij": "Save all"
             },
```
As far as I know, this no longer matches default Intellij behavior. Is this what was intended?

**Comment by k--kato** [comment]
@jibbers42 
I thought this issue means saving another file being edited by pressing cmd+s.
> As far as I know, this no longer matches default Intellij behavior
That's true. I'll revert this fix if they @gaoyuanfell @ixoster do not complain anything. 
Thanks

**Comment by jibbers42** [comment]
It's pretty easy to change the hotkey to do whichever behavior your want in the Keyboard Shortcuts. That's what I did after finding it no longer saved all files.

It seems like it would be best for an extension of this nature to match Intellij by default though, and then if someone doesn't want it to save all then it's easy enough to change it on their system (IMHO).

Anyway, thanks for the extension!

**Comment by k--kato** [comment]
Thanks
