### ISSUE TITLE
Installing from VS Code Marketplace installs version 0.1.1 instead of latest (0.2.6)

### ISSUE THREAD

**Issue by sommd** [k--kato/vscode-intellij-idea-keybindings#53]
Followed the instructions to install from README.MD, however the installed version is 0.1.1 (when you check in ~/.vscode/extensions) not the latest, even though the marketplace said it was on the latest version. Checked on Windows and Linux. Don't know if this is a problem with the marketplace or maybe CI.

**Comment by k--kato** [comment]
👍 I will release tonight (GMT+9).
duplicate  #51 #44
