### ISSUE TITLE
change case

### ISSUE THREAD

**Issue by hyt7212** [k--kato/vscode-intellij-idea-keybindings#66]
not support  

- Transform to Uppercase - editor.action.transformToUppercase
- Transform to Lowercase - editor.action.transformToLowercase

**Comment by k--kato** [comment]
@hyt7212  I love `Editor Actions | Toggle Case | Shift+Cmd+U`, but these command is not toggle. Wait until the toggle case is implemented in VS Code.

duplicated with #50
