### ISSUE TITLE
You're just amazing

### ISSUE THREAD

**Issue by egslava** [k--kato/vscode-intellij-idea-keybindings#68]
Guys, really sorry, I didn't know where to write it, but I think just "Star" is not enough. You're, guys, are JUST FFFF-ING AMAZING!!! THANK YOU _VERY_ MUCH for this addon!

I did some C++ in my childhood, now I've been doing Android apps for ~4 years. So C++ world is very interesting for me, but the lack of IDE on OS X is very discouraging. VS Code is super, but my experience with Android Studio (IDEA) is useless with these shortcuts. I changed some shortcuts on my own, but you've don COMPLETE HUGE WORK. And I feel really happy.

Thank you for you work again, guys. Thank you!

**Comment by k--kato** [comment]
Thanks @egslava ! This issue makes me happy, so I want to keep it open, but I have to close it.
