### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Yelfive** [k--kato/vscode-intellij-idea-keybindings#69]
I'm new to vscode, and today I installed the keymap and did the `enable>reload`

However, nothing happened, the keymap stays the same, what am I doing wrong.

It stuck me for hours  😂

**Comment by Chenjiufu** [comment]
1, maybe u not open this plug;
2, check whether other software global shortcuts repeated;

**Comment by Yelfive** [comment]
@Chenjiufu Thanks, my bad, I misunderstood the key bindings for intellij
