### ISSUE TITLE
idea-keybindings not working with file Java

### ISSUE THREAD

**Issue by DevAlves1993** [k--kato/vscode-intellij-idea-keybindings#76]
Hello,
Keybindings do not work with java files.
When I try to use the keybindings with another file it works.
I use the RedHat plugin (Language support for Java)

**Comment by k--kato** [comment]
Hi @DevAlves1993 ,

It worked in the following environment.

* VS Code: 1.12.2
* IntelliJ Idea Keybindings: 0.2.11
* Language Support for Java(TM) by Red Hat: 0.5.0
* Java Debugger: 0.1.0

![76](https://cloud.githubusercontent.com/assets/10364603/26745566/0c43bb98-4826-11e7-9879-3f7fd4fdf7ef.gif)

Can you show me your environment?

Thanks

**Comment by DevAlves1993** [comment]
Hi @k--kato,
my environment : 

- VS Code : 1.12.2
- IntelliJ Idea Keybindings : 0.2.11
- Language Support for Java(TM) by Red Hat : 0.5.0
- Java Debugger : not use
- OS : macOS X El Capitan

**Comment by k--kato** [comment]
Thank you for your env-info, @DevAlves1993 👍
I think that it will work well with your environment. 
1. Is Red Hat Java running?
1. Which key binding does not work?

**Comment by DevAlves1993** [comment]
1 - Yes Red Hat Java running.
2 - For moment i tried keys bindings shift+f6 (rename), which not working. But basic keys binding does works (cmd+b;alt+f7;...)

**Comment by DevAlves1993** [comment]
I think the problem is directly related to Red Hat Java.
The renaming functionality was opened in the Github Red Hat Java project : [issue](https://github.com/redhat-developer/vscode-java/issues/71)

**Comment by k--kato** [comment]
That makes sense. LSP has a symbol rename but can not rename the file now.
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#rename-request

**Comment by DevAlves1993** [comment]
Hello @k--kato,
Renaming works wonderfully now.
The renaming feature was implemented in the 0.9.0 version of the Red Hat Java extension.
