### ISSUE TITLE
Wrong Mac shortcuts to move lines/statements up/down

### ISSUE THREAD

**Issue by acim** [k--kato/vscode-intellij-idea-keybindings#90]
Here you use shift+cmd+up and shift-cmd-down and IntelliJ uses shift-alt-up and shift-alt-down

https://www.jetbrains.com/help/idea/adding-deleting-and-moving-code-elements.html

**Comment by k--kato** [comment]
@acim Thanks for your reporting and PR. I will release it today 👍

**Comment by acim** [comment]
No problem, thank you for merging 😊
